package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateWritesOnePagePerCommand(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, generate(dir))

	// 每个可见命令一个页面
	for _, name := range []string{
		"yews",
		"yews_init",
		"yews_encrypt",
		"yews_decrypt",
		"yews_plan",
		"yews_edit",
		"yews_view",
		"yews_diff",
		"yews_sync",
		"yews_completion",
	} {
		assert.FileExists(t, filepath.Join(dir, name+".md"))
	}

	// help 命令不生成页面
	assert.NoFileExists(t, filepath.Join(dir, "yews_help.md"))

	// 页面带有 VitePress frontmatter，没有自动生成的时间戳，且以单个换行符结尾
	content, err := os.ReadFile(filepath.Join(dir, "yews_encrypt.md"))
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(content), "---\ntitle: yews encrypt\n---\n"))
	assert.NotContains(t, string(content), "Auto generated by spf13/cobra")
	assert.True(t, strings.HasSuffix(string(content), "\n"))
	assert.False(t, strings.HasSuffix(string(content), "\n\n"))
}
