// Package sopsconfig renders the .sops.yaml file that YewSeal fully manages.
package sopsconfig

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/YewFence/YewSeal/internal/config"
	"gopkg.in/yaml.v3"
)

type sopsConfig struct {
	CreationRules []creationRule `yaml:"creation_rules"`
}

type creationRule struct {
	PathRegex string `yaml:"path_regex"`
	Age       string `yaml:"age"`
}

// Render returns the complete managed .sops.yaml content for resolved per-file
// policy. Writers and read-only drift checks share it so they cannot diverge.
func Render(filePairs []config.ResolvedFilePair) ([]byte, error) {
	creationRules := make([]creationRule, 0, len(filePairs))
	seen := make(map[string]string, len(filePairs))

	for _, filePair := range filePairs {
		if filePair.EncryptedPath == "" {
			continue
		}
		if len(filePair.Recipients) == 0 {
			return nil, fmt.Errorf("file %s has no resolved recipients", filePair.EncryptedPath)
		}

		pathRegex := buildPathRegex(filePair.EncryptedPath)
		recipients := append([]string(nil), filePair.Recipients...)
		sort.Strings(recipients)
		ageValue := strings.Join(recipients, ",")
		if previous, ok := seen[pathRegex]; ok {
			if previous != ageValue {
				return nil, fmt.Errorf("conflicting recipients for encrypted path %s", filePair.EncryptedPath)
			}
			continue
		}
		seen[pathRegex] = ageValue
		creationRules = append(creationRules, creationRule{
			PathRegex: pathRegex,
			Age:       ageValue,
		})
	}

	data, err := yaml.Marshal(&sopsConfig{CreationRules: creationRules})
	if err != nil {
		return nil, fmt.Errorf("failed to marshal YAML: %w", err)
	}
	return append([]byte("# Generated by YewSeal. DO NOT EDIT.\n# This file is fully managed and will be overwritten by init or enabled encrypt synchronization.\n"), data...), nil
}

func buildPathRegex(outputFile string) string {
	return "^" + regexp.QuoteMeta(outputFile) + "$"
}
