package project

import (
	"os"
	"testing"

	"github.com/YewFence/YewSeal/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSyncResolvedSopsYamlUsesPerFileRecipients(t *testing.T) {
	tmpDir := t.TempDir()
	withProjectWorkingDir(t, tmpDir)

	err := SyncResolvedSopsYaml([]config.ResolvedFilePair{
		{EncryptedPath: "prod.enc.yaml", Recipients: []string{"age1ops", "age1backup"}},
		{EncryptedPath: "dev.enc.yaml", Recipients: []string{"age1owner"}},
	})
	require.NoError(t, err)

	content, err := os.ReadFile(".sops.yaml")
	require.NoError(t, err)
	assert.Contains(t, string(content), "Generated by YewSeal. DO NOT EDIT.")
	assert.Contains(t, string(content), "age1backup,age1ops")
	assert.Contains(t, string(content), "age1owner")
}

func TestSyncResolvedSopsYamlRejectsConflictingDuplicatePath(t *testing.T) {
	withProjectWorkingDir(t, t.TempDir())
	err := SyncResolvedSopsYaml([]config.ResolvedFilePair{
		{EncryptedPath: "secret.enc.yaml", Recipients: []string{"age1owner"}},
		{EncryptedPath: "secret.enc.yaml", Recipients: []string{"age1ops"}},
	})
	require.EqualError(t, err, "conflicting recipients for encrypted path secret.enc.yaml")
}
