package project

import (
	"fmt"
	"os"
	"regexp"

	"github.com/YewFence/YewSeal/internal/config"
	"gopkg.in/yaml.v3"
	"sort"
	"strings"
)

const sopsYamlPath = ".sops.yaml"

// SopsConfig represents the structure of .sops.yaml
type SopsConfig struct {
	CreationRules []CreationRule `yaml:"creation_rules"`
}

// CreationRule represents a single rule in .sops.yaml
type CreationRule struct {
	PathRegex string `yaml:"path_regex"`
	Age       string `yaml:"age"`
}

// SyncResolvedSopsYaml rewrites .sops.yaml from resolved per-file policy.
func SyncResolvedSopsYaml(filePairs []config.ResolvedFilePair) error {
	return syncResolvedSopsYaml(filePairs)

}

func syncResolvedSopsYaml(filePairs []config.ResolvedFilePair) error {
	creationRules := make([]CreationRule, 0, len(filePairs))
	seen := make(map[string]string, len(filePairs))

	for _, filePair := range filePairs {
		if filePair.EncryptedPath == "" {
			continue
		}
		if len(filePair.Recipients) == 0 {
			return fmt.Errorf("file %s has no resolved recipients", filePair.EncryptedPath)
		}

		pathRegex := buildPathRegex(filePair.EncryptedPath)
		recipients := append([]string(nil), filePair.Recipients...)
		sort.Strings(recipients)
		ageValue := strings.Join(recipients, ",")
		if previous, ok := seen[pathRegex]; ok {
			if previous != ageValue {
				return fmt.Errorf("conflicting recipients for encrypted path %s", filePair.EncryptedPath)
			}
			continue
		}
		seen[pathRegex] = ageValue
		creationRules = append(creationRules, CreationRule{
			PathRegex: pathRegex,
			Age:       ageValue,
		})
	}

	if err := writeSopsConfig(SopsConfig{CreationRules: creationRules}); err != nil {
		return err
	}

	fmt.Printf("✅ Synced .sops.yaml with %d rule(s)\n", len(creationRules))
	return nil
}

func writeSopsConfig(config SopsConfig) error {
	data, err := yaml.Marshal(&config)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}

	data = append([]byte("# Generated by YewSeal. DO NOT EDIT.\n# This file is fully managed and will be overwritten by init/sync/encrypt.\n"), data...)
	tempFile, err := os.CreateTemp(".", ".sops.yaml.*")
	if err != nil {
		return fmt.Errorf("failed to create temporary .sops.yaml: %w", err)
	}
	tempPath := tempFile.Name()
	defer func() { _ = os.Remove(tempPath) }()
	if _, err := tempFile.Write(data); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("failed to write temporary .sops.yaml: %w", err)
	}
	if err := tempFile.Chmod(0644); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("failed to set temporary .sops.yaml permissions: %w", err)
	}
	if err := tempFile.Sync(); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("failed to sync temporary .sops.yaml: %w", err)
	}
	if err := tempFile.Close(); err != nil {
		return fmt.Errorf("failed to close temporary .sops.yaml: %w", err)
	}
	if err := os.Rename(tempPath, sopsYamlPath); err != nil {
		return fmt.Errorf("failed to replace .sops.yaml: %w", err)
	}

	return nil
}

func buildPathRegex(outputFile string) string {
	escapedOutput := regexp.QuoteMeta(outputFile)
	return "^" + escapedOutput + "$"
}
