package verify

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"regexp"
	"strings"

	"github.com/YewFence/YewSeal/internal/config"
	"gopkg.in/yaml.v3"
)

const sopsYamlPath = ".sops.yaml"

// checkSOPSDrift compares the on-disk .sops.yaml with what SyncResolvedSopsYaml
// would generate for the same filePairs. If they diverge, it is an error.
// If .sops.yaml is absent, it is a skip.
func checkSOPSDrift(report *Report, filePairs []config.ResolvedFilePair) {
	onDisk, err := os.ReadFile(sopsYamlPath)
	if os.IsNotExist(err) {
		report.AddSkip(".sops.yaml does not exist; drift check skipped")
		return
	}
	if err != nil {
		report.Add(Finding{
			Code:    "sops_config_read_error",
			Severity: SeverityError,
			Message: fmt.Sprintf("failed to read .sops.yaml: %v", err),
		})
		return
	}

	expected, err := generateSopsYAML(filePairs)
	if err != nil {
		report.Add(Finding{
			Code:     "sops_config_generate_error",
			Severity: SeverityError,
			Message:  fmt.Sprintf("failed to generate expected .sops.yaml content: %v", err),
		})
		return
	}

	if bytes.Equal(normalizeYAML(onDisk), normalizeYAML(expected)) {
		report.AddPass()
		return
	}

	report.Add(Finding{
		Code:     "sops_config_drift",
		Severity: SeverityError,
		Message:  ".sops.yaml does not match the resolved project policy",
		Hint:     "run 'yews encrypt --sync-sops-config' or 'yews encrypt' (sync is on by default) to regenerate it",
	})
}

func generateSopsYAML(filePairs []config.ResolvedFilePair) ([]byte, error) {
	type creationRule struct {
		PathRegex string `yaml:"path_regex"`
		Age       string `yaml:"age"`
	}
	type sopsConfig struct {
		CreationRules []creationRule `yaml:"creation_rules"`
	}

	seen := make(map[string]string, len(filePairs))
	rules := make([]creationRule, 0, len(filePairs))

	for _, pair := range filePairs {
		if pair.EncryptedPath == "" || len(pair.Recipients) == 0 {
			continue
		}
		pathRegex := "^" + regexp.QuoteMeta(pair.EncryptedPath) + "$"
		recipients := append([]string(nil), pair.Recipients...)
		sort.Strings(recipients)
		ageValue := strings.Join(recipients, ",")
		if prev, ok := seen[pathRegex]; ok && prev != ageValue {
			return nil, fmt.Errorf("conflicting recipients for %s", pair.EncryptedPath)
		}
		if _, ok := seen[pathRegex]; ok {
			continue
		}
		seen[pathRegex] = ageValue
		rules = append(rules, creationRule{PathRegex: pathRegex, Age: ageValue})
	}

	data, err := yaml.Marshal(sopsConfig{CreationRules: rules})
	if err != nil {
		return nil, err
	}
	return append([]byte("# Generated by YewSeal. DO NOT EDIT.\n# This file is fully managed and will be overwritten by init or enabled encrypt synchronization.\n"), data...), nil
}

// normalizeYAML strips comments and normalizes whitespace for comparison.
func normalizeYAML(data []byte) []byte {
	var v any
	if err := yaml.Unmarshal(data, &v); err != nil {
		return data
	}
	out, err := yaml.Marshal(v)
	if err != nil {
		return data
	}
	return out
}
